on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build jar
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:${{ github.sha }}

      - name: 🚀 Deploy to Lightsail Instance via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Use your existing secrets
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          
          # Commands executed on the Lightsail Instance
          script: |
            echo "--- Starting Deployment on Lightsail Instance ---"
            
            # 1. Log in to Docker Hub on the instance
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            # 2. Pull the newly pushed image
            # Use the latest tag for ease, but map it to the SHA tag
            IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/my-spring-app:${{ github.sha }}
            docker pull $IMAGE_TAG
            
            # 3. Stop and remove the old container (if running)
            docker stop my-spring-app-container || true
            docker rm my-spring-app-container || true
            
            # 4. Start the new container
            docker run -d \
              --name my-spring-app-container \
              -p 8080:8080 \
              $IMAGE_TAG
            
            echo "--- Deployment Complete! Container running on port 8080. ---"