name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/deployer
            rm -rf spring-app
            git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Vishwa-programmer/spring-app.git spring-app
            cd spring-app
            chmod +x deploy.sh
            ./deploy.sh